services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bancors_bd
    restart: always
    networks:
      - spring

  bancors:
    container_name: bancors
    build:
      context: ./
      dockerfile: ./bancors/Dockerfile
    ports:
        - "8003:8003"
    environment:
      PORT: 8003
      BD_HOST: mysql8:3306
      DB_DATABASE: bancors_bd
      BD_USERNAME: root
      BD_PASSWORD: admin
      BANCORS_URL: bancors:8003
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

networks:
  spring:
    name: spring
    external: true